# Generated by Django 3.2.5 on 2021-07-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=35)),
                ('gender', models.CharField(max_length=12)),
                ('culture', models.CharField(blank=True, max_length=20, null=True)),
                ('born', models.CharField(blank=True, max_length=20, null=True)),
                ('died', models.CharField(blank=True, max_length=20, null=True)),
                ('titles', models.JSONField()),
                ('aliases', models.JSONField()),
                ('father', models.JSONField()),
                ('mother', models.JSONField()),
                ('spouse', models.CharField(blank=True, max_length=100, null=True)),
                ('allegiances', models.JSONField()),
                ('books', models.JSONField()),
                ('povBooks', models.JSONField()),
                ('tvSeries', models.JSONField()),
                ('playedBy', models.JSONField()),
            ],
        ),
    ]
