# Generated by Django 3.2.5 on 2021-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameOfThrones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='url',
        ),
        migrations.AlterField(
            model_name='characters',
            name='books',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='characters',
            name='father',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='characters',
            name='id',
            field=models.IntegerField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='characters',
            name='mother',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='characters',
            name='povBooks',
            field=models.TextField(),
        ),
    ]
