# Generated by Django 3.2.5 on 2021-07-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameOfThrones', '0002_auto_20210715_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
