# Generated by Django 3.2.5 on 2021-07-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameOfThrones', '0004_alter_characters_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='books',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='characters',
            name='povBooks',
            field=models.JSONField(),
        ),
    ]
